version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Application code
      - .:/app
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Mount data directory for generated files
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-1106-preview}
    command: python web_app.py
