version: '3.8'

services:
  ai-agent:
    build: .
    volumes:
      - .:/app
      # Mount a logs directory to persist logs
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      #to change model interactively use: OPENAI_MODEL=gpt-3.5-turbo docker-compose up
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-1106-preview}
    command: --goal "list files in current directory" --config /app/config.yaml
